"use client";

import BackButton from "@/components/nav/BackButton";
import { TechBar } from "@/components/BottomBar";

export default function PrivacyPage() {
  // Replace the placeholder text below with your actual privacy policy.
  const policyContent = (
    <div className="space-y-8">
      <section>
        <h2 className="text-2xl font-bold text-white">Privacy Policy</h2>
        <p className="text-sm text-zinc-400">Last updated: 18/02/2026</p>
      </section>

      <section>
        <h3 className="text-xl font-semibold text-white">1. Introduction</h3>
        <p className="text-zinc-300">
          This Privacy Policy explains how we collect, use, and protect your
          personal data when you use our application (“the Service”). By using
          the Service, you agree to the collection and use of information in
          accordance with this policy.
        </p>
      </section>

      <section>
        <h3 className="text-xl font-semibold text-white">2. Data We Collect</h3>
        <p className="text-zinc-300">
          We may collect and store the following information:
        </p>
        <ul className="list-disc pl-6 text-zinc-300 space-y-1">
          <li>Email address (for authentication)</li>
          <li>User ID (generated by the authentication system)</li>
          <li>
            Profile information (such as name, title, skills, introduction, and
            projects)
          </li>
          <li>Links to external profiles (GitHub, LinkedIn)</li>
          <li>Account creation date</li>
        </ul>
        <p className="mt-2 text-zinc-300">
          We do not collect sensitive personal data such as financial information, health data, or government-issued identification numbers. Please do not provide such information through the Service.
        </p>
      </section>

      <section>
        <h3 className="text-xl font-semibold text-white">
          3. How We Use Your Data
        </h3>
        <p className="text-zinc-300">
          Your data is used for the following purposes:
        </p>
        <ul className="list-disc pl-6 text-zinc-300 space-y-1">
          <li>To provide and maintain the Service</li>
          <li>To create and display user profiles</li>
          <li>To authenticate users</li>
          <li>To improve and maintain the functionality of the application</li>
          <li>To respond to user support requests</li>
        </ul>
        <p className="mt-2 text-zinc-300">We do not sell your personal data.</p>
      </section>

      <section>
        <h3 className="text-xl font-semibold text-white">
          4. Data Storage and Security
        </h3>
        <p className="text-zinc-300">
          Your data is stored securely using third-party infrastructure provided
          by:
        </p>
        <ul className="list-disc pl-6 text-zinc-300 space-y-1">
          <li>Supabase (database and authentication)</li>
          <li>Vercel</li>
        </ul>
        <p className="mt-2 text-zinc-300">
          We use industry-standard security measures, including authentication
          and access control, to protect your information. However, no method of
          transmission over the internet is 100% secure, and we cannot guarantee
          absolute security.
        </p>
      </section>

      <section>
        <h3 className="text-xl font-semibold text-white">
          5. Third-Party Services
        </h3>
        <p className="text-zinc-300">
          We use the following third-party services to operate the Service:
        </p>
        <ul className="list-disc pl-6 text-zinc-300 space-y-1">
          <li>Supabase (authentication and database)</li>
          <li>Hosting provider (Vercel)</li>
        </ul>
        <p className="mt-2 text-zinc-300">
          These providers process data only as necessary to provide their
          services and in accordance with their own privacy policies.
        </p>
      </section>

      <section>
        <h3 className="text-xl font-semibold text-white">6. Public Profiles</h3>
        <p className="text-zinc-300">
          Some profile information may be publicly visible to other users or
          visitors. You are responsible for any information you choose to make
          public.
        </p>
      </section>

      <section>
        <h3 className="text-xl font-semibold text-white">
          7. Your Rights (GDPR)
        </h3>
        <p className="text-zinc-300">
          If you are located in the European Union, you have the right to:
        </p>
        <ul className="list-disc pl-6 text-zinc-300 space-y-1">
          <li>Access your personal data</li>
          <li>Correct inaccurate data</li>
          <li>Request deletion of your data</li>
          <li>Restrict or object to processing</li>
          <li>Request data portability</li>
        </ul>
        <p className="mt-2 text-zinc-300">
          You may exercise these rights by contacting us.
        </p>
      </section>

      <section>
        <h3 className="text-xl font-semibold text-white">8. Data Retention</h3>
        <p className="text-zinc-300">
          We retain your data only for as long as your account remains active.
          When you delete your account, your personal data is removed from our
          systems, unless legal obligations require otherwise.
        </p>
      </section>

      <section>
        <h3 className="text-xl font-semibold text-white">
          9. Children’s Privacy
        </h3>
        <p className="text-zinc-300">
          The Service is not intended for users under the age of 13. We do not
          knowingly collect personal data from children.
        </p>
      </section>

      <section>
        <h3 className="text-xl font-semibold text-white">
          10. Changes to This Policy
        </h3>
        <p className="text-zinc-300">
          We may update this Privacy Policy from time to time. Any changes will
          be posted on this page with an updated “Last updated” date.
        </p>
      </section>

      <section>
        <h3 className="text-xl font-semibold text-white">
          11. Contact Information
        </h3>
        <p className="text-zinc-300">
          If you have any questions about this Privacy Policy or your personal
          data, please contact:
        </p>
        <ul className="list-disc pl-6 text-zinc-300 space-y-1">
          <li>Name: Karri Partanen</li>
          <li>Email: karri.t.partanen@gmail.com</li>
        </ul>
      </section>
    </div>
  );

  return (
    <main className="min-h-screen bg-zinc-950 relative overflow-hidden pt-16 sm:pt-0 text-white">
      {/* ambient blobs */}
      <div className="absolute top-[-20%] left-[-10%] w-125 h-125 bg-blue-500/30 rounded-full blur-3xl" />
      <div className="absolute bottom-[-20%] right-[-10%] w-125 h-125 bg-purple-500/30 rounded-full blur-3xl" />

      <BackButton
        to="/"
        label="Back to Home"
        variant="ghost"
        className="fixed top-6 left-4 sm:top-4 z-10"
      />

      <section className="relative z-10 px-6 pt-24 pb-12 sm:pt-28 sm:pb-16 max-w-4xl mx-auto">
        <h1 className="text-4xl sm:text-5xl font-extrabold tracking-tight text-white text-center">
          Privacy Policy
        </h1>
        <p className="mt-3 text-zinc-400 text-center max-w-2xl mx-auto">
          This page presents the privacy policy for the application.
        </p>

        <div className="mt-8 rounded-2xl bg-linear-to-br from-zinc-900 to-zinc-800 border border-white/10 p-6">
          {policyContent}
        </div>
      </section>

      <TechBar />
    </main>
  );
}
